apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dev-chat-front
  labels:
    app: dev-chat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-chat-front
  template:
    metadata:
      labels:
        app: dev-chat-front
    spec:
      containers:
      - name: dev-chat-front
        imagePullPolicy: Always
        image: ghcr.io/tous-project/chat-front/chat-front:35813122a5a283d17960090e7c3538dcf99e6307
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 30m
---
apiVersion: v1
kind: Service
metadata:
  name: dev-chat-front-service
spec:
  type:  NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
    name: http
  selector:
    app: dev-chat-front
