apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-database
  labels:
    app: dev-database
spec:
  selector:
    matchLabels:
      app: dev-database
  template:
    metadata:
      labels:
        app: dev-database
    spec:
      containers:
      - image: redis:7-alpine3.17
        name: dev-redis
        resources:
          limits:
            memory: 128Mi
            cpu: 30m
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
      - image: postgres:15.0
        name: dev-postgres
        resources:
          limits:
            memory: 256Mi
            cpu: 30m
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: user_name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: database
              key: db_name
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name:  dev-database-service
  labels:
    app: dev-database-service
spec:
  selector:
    app: dev-database
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30004
      protocol: TCP
      name: dev-postgres
    - port: 6379
      targetPort: 6379
      nodePort: 30005
      protocol: TCP
      name: dev-redis
