apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dev-chat-server-deployment
  labels:
    app: dev-chat-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-chat-server
  template:
    metadata:
      labels:
        app: dev-chat-server
    spec:
      containers:
      - name: dev-chat-server
        imagePullPolicy: Always
        image: ghcr.io/tous-project/chat-server/chat-server:dev0.3.1
        command: ["python3"]
        args: ["main.py"]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: database
              key: dsn
        resources:
          limits:
            memory: 256Mi
            cpu: 30m
---
apiVersion: v1
kind: Service
metadata:
  name: dev-chat-server-service
spec:
  type:  NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30003
    protocol: TCP
    name: http
  selector:
    app: dev-chat-server
