apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name:  dev-chat-server-rollout
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 60}
        - setWeight: 40
        - pause: {duration: 60}
        - setWeight: 60
        - pause: {duration: 60}
        - setWeight: 80
        - pause: {duration: 60}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dev-chat-server
  template:
    metadata:
      labels:
        app: dev-chat-server
    spec:
      containers:
      - name: dev-chat-server
        imagePullPolicy: Always
        image: ghcr.io/tous-project/chat-server/chat-server:dev0.2.0
        command: ["python3"]
        args: ["main.py"]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: database
              key: dsn
        resources:
          limits:
            memory: 512mi
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: dev-chat-server-service
spec:
  type:  NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30003
    protocol: TCP
    name: http
  selector:
    app: dev-chat-server
